sudo: false
language: go

go:
  - 1.x

services:
  - mysql

matrix:
  fast_finish: true

before_script:
  - echo "USE mysql;\nupdate user set authentication_string=PASSWORD("root") where User='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - go get -t -v ./...
  - go vet ./...
  - go test -p 1 ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
