sudo: false
language: go

go:
  - 1.x

services:
  - mysql

matrix:
  fast_finish: true

script:
  - go get -t -v ./...
  - go vet ./...
  - go test -v -p 1 ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
