sudo: false
language: go

go:
  - "1.14"
  - "1.15"
  - "1.16"
  - master

services:
  - mysql

matrix:
  fast_finish: true

before_script:
  - env GO111MODULE=on
  - mysql -e 'USE mysql;update user set authentication_string=password("root") where user="root";FLUSH PRIVILEGES'

script:
  - env GO111MODULE=on go get -t -v ./...
  - env GO111MODULE=on go vet ./...
  - env GO111MODULE=on go test -race -p 1 -coverpkg=github.com/patrickascher/gofer/... -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
